CREATE TABLE IF NOT EXISTS PURCHASES
(
   ID_NUM INT IDENTITY,
   NAME VARCHAR(50),
   PDATE TIMESTAMP,
   COST DOUBLE,
   STATE CHAR(2),
   SHIPPING_TYPE VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS USERS
(
   ID_NUM INT IDENTITY,
   NAME VARCHAR(50),
   PASSWORD VARCHAR(50)
);